language: node_js
node_js:
  - "6"
before_script:
  - yarn run bootstrap
script:
  - yarn run build
  - yarn run lint
  - yarn test -- --runInBand
deploy:
  provider: script
  script: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc && yarn && yarn run publish
  on:
    branch: master
