language: node_js
node_js:
  - "6"
before_script:
  - yarn run bootstrap
script:
  - yarn run commitmsg -- "$(git log master..$TRAVIS_BRANCH --pretty=%B)"
  - yarn run build
  - yarn run lint
  - yarn test -- --runInBand
